# Generated by Django 5.0.4 on 2024-04-14 09:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название записи')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='URL')),
                ('text', models.TextField(max_length=700, verbose_name='Текст записи')),
                ('thumbnail', models.ImageField(blank=True, default='default.jpg', upload_to='images/thumbnail/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'webp', 'gif'))], verbose_name='Изображение записи')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=13, verbose_name='Статусы записей')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'blog_post',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created', '-status'], name='blog_post_created_b32ac8_idx')],
            },
        ),
    ]
