# Generated by Django 5.0.4 on 2024-04-14 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legend_blog', '0002_postreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('user', 'post')},
        ),
    ]
