# Generated by Django 5.0.4 on 2024-04-15 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_blog', '0004_alter_postreaction_options_alter_postreaction_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=700, validators=[django.core.validators.MinLengthValidator(31)], verbose_name='Текст записи'),
        ),
    ]
