# Generated by Django 5.0.4 on 2024-04-16 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_blog', '0005_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=950, validators=[django.core.validators.MinLengthValidator(31)], verbose_name='Текст записи'),
        ),
    ]
